module "ldap-server" {
  source                  = "ldap-server"
  availability_domain     = "${var.ads[var.availability_domains_idx]}"
  compartment_ocid        = "${var.compartment_ocid}"
  shape                   = "${var.ServerInstanceShape}"
  ssh_public_key          = "${var.ssh_public_key}"
  ssh_private_key         = "${var.ssh_private_key}"
  image_id                = "${var.ServerInstanceImageOCID[var.region]}"
  region                  = "${var.region}"
  subnet_id               = "${var.server_subnet_id}"
  bastion_host            = "${var.bastion_host}"
  bastion_user            = "${var.bastion_user}"
  bastion_ssh_private_key = "${var.bastion_ssh_private_key}"
  ldap_domain_name         = "${var.ldap_domain_name}"
  ldap_sudo_group_name     = "${var.ldap_sudo_group_name}"
}

module "ldap-client" {
  source                  = "ldap-client"
  client_count            = "${var.client_count}"
  availability_domain     = "${var.ads[var.availability_domains_idx]}"
  compartment_ocid        = "${var.compartment_ocid}"
  shape                   = "${var.ClientInstanceShape}"
  ssh_public_key          = "${var.ssh_public_key}"
  ssh_private_key         = "${var.ssh_private_key}"
  image_id                = "${var.ClientInstanceImageOCID[var.region]}"
  region                  = "${var.region}"
  subnet_id               = "${var.client_subnet_id}"
  server_host_name        = "${module.ldap-server.host_name}"
  server_domain_name      = "${module.ldap-server.domain_name}"
  server_id               = "${module.ldap-server.id}"
  bastion_host            = "${var.bastion_host}"
  bastion_user            = "${var.bastion_user}"
  bastion_ssh_private_key = "${var.bastion_ssh_private_key}"
  ldap_domain_name         = "${var.ldap_domain_name}"
  ldap_sudo_group_name     = "${var.ldap_sudo_group_name}"
}
