ldap_login_host_public_ip        = "129.213.97.77"
ldap_login_user                  = "opc"
ldap_login_host_ssh_private_key  = "/home/opc/.ssh/id_rsa"
ldap_server_hostname             = "ldap-server"
ldap_server_domainname           = "ldapser.ldap.oraclevcn.com"
ldap_domain_name                 = "ldapser.ldap.oraclevcn.com"
ldap_server_private_ip           = "10.0.1.2"
ldap_server_user                 = "opc"
ldap_server_ssh_private_key      = "/home/opc/.ssh/id_rsa"
ldap_server_sercure_net_list     = ["255.255.0.0", "10.0.0.0"]
ldap_client_private_ip_list      = ["10.0.0.19", "10.0.0.18"]
ldap_client_private_user_list    = ["opc", "opc"]
ldap_client_ssh_private_key_list = ["/home/opc/.ssh/id_rsa", "/home/opc/.ssh/id_rsa"]
